// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kklvthnshgqhmdhuuhzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtrbHZ0aG5zaGdxaG1kaHV1aHpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MTAzNjAsImV4cCI6MjA2ODA4NjM2MH0.v4yMh_ZbRUsPo2xTqBr-Zoj5S4ZhGK6OnWf1oTPhACs";


// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true
    }
  }
);