// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cotmxmhjmspffvljhuaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvdG14bWhqbXNwZmZ2bGpodWF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNDQ4MjAsImV4cCI6MjA2NzgyMDgyMH0.oSc82tQpda2PaihQUN4dcEAniH75DrXZgLY8DXd2rlY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});