// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hbuzettdestumvsfptvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhidXpldHRkZXN0dW12c2ZwdHZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNDE5ODIsImV4cCI6MjA2NzgxNzk4Mn0.uyqWQ7120YnnA46wTXQM7kyE9cui3LNmBUQxngcRdoY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});